name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Setup pnpm for CI/CD
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          node-version: 24
          pnpm-version: 10

      - name: Lint
        run: pnpm lint:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Setup pnpm for CI/CD
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          node-version: 24
          pnpm-version: 10

      - name: Lint
        run: pnpm lint:backend
  
  frontend-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Setup pnpm for CI/CD
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          node-version: 24
          pnpm-version: 10

      - name: Test
        run: pnpm test:frontend
    
  backend-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup pnpm for CI/CD
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          node-version: 24
          pnpm-version: 10

      - name: Test
        run: pnpm test:backend