name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile 

      - name: Lint
        run: pnpm lint:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile 

      - name: Lint
        run: pnpm lint:backend
  
  frontend-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile --no-verify-store-integrity

      - name: Test
        run: pnpm test:frontend
    
  backend-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile 

      - name: Test
        run: pnpm test:backend